name: trosy_driver
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^3.4.0
  cloud_firestore: ^5.4.0
  firebase_auth: ^5.3.0

  # GPS
  geolocator: ^12.0.0
  location: ^7.0.0

  # MapLibre
  maplibre_gl: ^0.22.0
