name: Deploy Flutter Web

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install FVM
        run: |
          dart pub global activate fvm

      - name: Install Flutter 3.22.2 via FVM
        run: |
          dart pub global run fvm install 3.22.2
          dart pub global run fvm use 3.22.2 --force
          echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH

      - name: Use Flutter
        run: |
          fvm flutter --version
          fvm flutter config --enable-web

      - name: Get dependencies
        run: fvm flutter pub get

      - name: Build Web
        run: fvm flutter build web --release --base-href /trosy_driver/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          publish_branch: gh-pages
